# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [6]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

np_height=np.array(height) 
np_weight=np.array(weight)
BMI=np_height /np_weight **2 
print(BMI)

[0.00570248 0.00486111 0.00420118 0.00367347 0.00324444 0.00289062
 0.00259516]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [6]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass
import random

import numpy as np

def random_matrix(R, cols):

    matrix = []

    rows =  0

    while  rows < cols:

        N = random.sample(R, cols)

        matrix.append(N)

        rows = rows + 1

    return np.array(matrix)

print(random_matrix(range(10), 5))

[[2 8 7 3 0]
 [8 4 7 5 3]
 [0 7 3 5 1]
 [0 7 9 6 5]
 [6 7 5 4 1]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [4]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [15]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1, usecols = np.arange(0,24),invalid_raise = False, names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')
print (bs2017)

names = bs2017['Name']
#print(names)

bs2017 = slg2017
print(slg)

#Find Total SLG2017
total_slg2017 = sum(bs2017['arr_list1'])
print[f'\n Total SLG:{total_slg}']

bs2018 = load_data('../files/redsox_2018_hitting.txt')
#print(bs2018)

names = bs2018['Name']
#print(names)

bs2018 = slg2018
print(slg)

#Find Total SLG2018
total_slg2-18 = sum(bs2018['arr_list2'])
print[f'\n Total SLG:{total_slg}']

result_diff = abs(arr_list1 - arr_list2)
result_diff

print(result_diff)
      





SyntaxError: cannot assign to operator (<ipython-input-15-59514021c113>, line 45)